import assert from "node:assert/strict";
import { client } from "./helpers.mjs";
import test from "node:test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { startPlayer } from "../../../server/index.mjs";
import { scorm12Zip } from "../../../tests/fixtures.mjs";

test("standalone bundled MCP shares pins, serves inline UI and rejects stale revisions", async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "scorm-mcp-"));
  const registry = path.join(dir, "registry");
  const zip = path.join(dir, "course.zip");
  fs.writeFileSync(zip, scorm12Zip());
  const player = await startPlayer({ input: zip, port: 0, registryDir: registry, cacheDir: path.join(dir, "cache") });
  // Run without a node_modules tree or workspace-relative dependencies.
  const installed = path.join(dir, ".installed");
  fs.mkdirSync(installed);
  const entry = path.join(installed, "server.mjs");
  fs.copyFileSync(fileURLToPath(new URL("../dist/server.mjs", import.meta.url)), entry);
  fs.copyFileSync(fileURLToPath(new URL("../dist/review.html", import.meta.url)), path.join(installed, "review.html"));
  fs.copyFileSync(fileURLToPath(new URL("../dist/skills.json", import.meta.url)), path.join(installed, "skills.json"));
  for (const name of ["player-client", "assets"]) fs.cpSync(fileURLToPath(new URL(`../dist/${name}`, import.meta.url)), path.join(installed, name), { recursive: true });
  const openerDir = path.join(dir, "bin");
  const launchLog = path.join(dir, "browser-launches.jsonl");
  fs.mkdirSync(openerDir);
  for (const name of ["open", "xdg-open"]) fs.writeFileSync(path.join(openerDir, name), `#!${process.execPath}\nrequire("node:fs").appendFileSync(${JSON.stringify(launchLog)}, JSON.stringify(process.argv.slice(2))+"\\n");\n`, { mode: 0o755 });
  const rpc = client(entry, registry, dir, process.execPath, { PATH: `${openerDir}${path.delimiter}${process.env.PATH}` });
  const call = async (name, args = {}) => {
    const response = await rpc.request("tools/call", { name, arguments: args });
    assert.equal(response.error, undefined, JSON.stringify(response.error));
    return response.result;
  };
  try {
    const init = await rpc.request("initialize", { protocolVersion: "2025-11-25", capabilities: {}, clientInfo: { name: "test", version: "1" } });
    assert.equal(init.error, undefined, JSON.stringify(init.error));
    assert.equal(init.result.serverInfo.name, "scormplayer");
    rpc.notify("notifications/initialized");
    const listing = await rpc.request("tools/list");
    assert.equal(listing.error, undefined, JSON.stringify(listing.error));
    assert.ok(listing.result.tools.length >= 10);
    assert.equal(listing.result.tools.some((tool) => tool.name === "scormplayer_open_workspace"), false);
    assert.equal(listing.result.tools.some((tool) => tool._meta?.["openai/ui"]?.entrypoints), false);
    const pinTool = listing.result.tools.find((tool) => tool.name === "scormplayer_list_pins");
    assert.equal(pinTool._meta.ui.resourceUri, "ui://scormplayer/pin-checklist.html");
    const browserTool = listing.result.tools.find((tool) => tool.name === "scormplayer_start");
    assert.equal(browserTool._meta?.ui, undefined, "normal startup does not open an extension");
    const started = await call("scormplayer_start", { path: zip });
    assert.equal(started.isError, undefined, JSON.stringify(started));
    assert.equal(fs.existsSync(path.join(dir, "agent", "tls")), false, "normal MCP startup never creates certificates");
    const owned = started.structuredContent;
    const browserScope = { playerId: owned.playerId, revision: started.structuredContent.revision };
    const browserLaunch = await call("scormplayer_open_browser", browserScope);
    assert.equal(browserLaunch.structuredContent.launched, true);
    assert.deepEqual(JSON.parse(fs.readFileSync(launchLog, "utf8").trim()), [owned.url]);
    assert.equal((await call("scormplayer_open_browser", { ...browserScope, revision: "retired" })).isError, true);
    assert.equal(fs.readFileSync(launchLog, "utf8").trim().split("\n").length, 1, "stale scope must not launch a browser");
    fs.rmSync(path.join(installed, "player-client"), { recursive: true });
    fs.rmSync(path.join(installed, "review.html"));
    assert.equal((await fetch(owned.url)).status, 200, "running player survives host removal of old installed assets");
    const page = await (await fetch(owned.url)).text();
    const assets = [...page.matchAll(/(?:src|href)="([^" ]+\.(?:js|css))"/g)].map((match) => match[1]);
    assert.ok(assets.length >= 2);
    for (const asset of assets) {
      const response = await fetch(new URL(asset, owned.url));
      assert.equal(response.status, 200, asset);
      assert.match(response.headers.get("content-type"), /javascript|css/, asset);
    }
    const empty = (await call("scormplayer_get_status", { playerId: owned.playerId })).structuredContent;
    assert.equal(empty.course.kind, "package");
    const rejectedUpload = await fetch(new URL("api/open", owned.url), { method: "POST", headers: { origin: "https://other-site.example", "x-file-name": "uploaded.zip", "x-scormplayer-revision": empty.revision }, body: scorm12Zip() });
    assert.equal(rejectedUpload.status, 403);
    const upload = await fetch(new URL("api/open", owned.url), { method: "POST", headers: { origin: new URL(owned.url).origin, "x-file-name": "uploaded.zip", "x-scormplayer-revision": empty.revision }, body: scorm12Zip() });
    assert.equal(upload.status, 200, await upload.text());
    const loaded = (await call("scormplayer_get_status", { playerId: owned.playerId })).structuredContent;
    assert.equal(loaded.course.kind, "package");
    assert.notEqual(loaded.revision, empty.revision);
    assert.equal((await call("scormplayer_open_lesson", { playerId: owned.playerId, revision: empty.revision, path: zip })).isError, true);
    assert.equal((await call("scormplayer_open_lesson", { playerId: owned.playerId, revision: loaded.revision, path: zip })).isError, undefined);
    const liveRoot = path.join(dir, "live-source");
    fs.mkdirSync(liveRoot);
    fs.writeFileSync(path.join(liveRoot, "package.json"), '{"type":"module"}');
    fs.writeFileSync(path.join(liveRoot, "vite.config.mjs"), "export default {};");
    fs.writeFileSync(path.join(liveRoot, "index.html"), '<h1>Live lesson</h1><script type="module" src="/lesson.js"></script>');
    fs.writeFileSync(path.join(liveRoot, "lesson.js"), 'document.querySelector("h1").textContent="Before";');
    fs.symlinkSync(fileURLToPath(new URL("../../../node_modules", import.meta.url)), path.join(liveRoot, "node_modules"), "junction");
    const beforeLive = (await call("scormplayer_get_status", { playerId: owned.playerId })).structuredContent;
    const openedLive = await call("scormplayer_open_lesson", { playerId: owned.playerId, revision: beforeLive.revision, path: liveRoot, live: true });
    assert.equal(openedLive.isError, undefined, JSON.stringify(openedLive));
    const liveStatus = (await call("scormplayer_get_status", { playerId: owned.playerId })).structuredContent;
    assert.equal(liveStatus.course.kind, "live");
    assert.match(await (await fetch(new URL("course/", owned.url))).text(), /@vite\/client/);
    assert.match(await (await fetch(new URL("course/lesson.js", owned.url))).text(), /Before/);
    const found = await call("scormplayer_list_players");
    assert.equal(found.structuredContent.players.length, 2);
    const playerId = found.structuredContent.players.find((p) => p.url === player.url).playerId;
    const status = await call("scormplayer_get_status", { playerId });
    assert.equal(status.isError, undefined, JSON.stringify(status));
    const { revision } = status.structuredContent;
    const scope = { playerId, revision };
    const progress = await call("scormplayer_get_progress", scope);
    assert.equal(progress.isError, undefined, JSON.stringify(progress));
    assert.equal(progress.structuredContent.saved, false);
    assert.deepEqual(progress.structuredContent.modules, {});
    const save = await fetch(new URL("api/scorm", player.url), { method: "PUT", headers: { "content-type": "application/json", "x-scormplayer-revision": revision }, body: JSON.stringify({ epoch: 0, selectedSco: "", modules: { "": { "cmi.core.lesson_location": "slide-2", "cmi.suspend_data": "resume-me", "cmi.core.lesson_status": "incomplete" } } }) });
    assert.equal(save.status, 200);
    const savedProgress = await call("scormplayer_get_progress", scope);
    assert.equal(savedProgress.structuredContent.saved, true);
    assert.equal(savedProgress.structuredContent.modules[""]["cmi.core.lesson_location"], "slide-2");
    assert.equal(savedProgress.structuredContent.modules[""]["cmi.suspend_data"], "resume-me");
    assert.equal((await call("scormplayer_get_progress", { ...scope, revision: "old" })).isError, true);
    const pin = player.pins.create({ note: "Review this copy", target: { name: "Intro", selector: "#intro" } });
    const pins = await call("scormplayer_list_pins", scope);
    assert.equal(pins.structuredContent.pins[0].id, pin.id);
    const changed = await call("scormplayer_update_pin", { ...scope, id: pin.id, note: "Updated through MCP" });
    assert.equal(changed.isError, undefined);
    assert.equal(player.pins.list()[0].note, "Updated through MCP");
    const handoff = await call("scormplayer_get_handoff", { ...scope, ids: [pin.id] });
    assert.match(handoff.structuredContent.markdown, /Updated through MCP/);
    assert.equal((await call("scormplayer_update_pin", { ...scope, revision: "old", id: pin.id, note: "Wrong course" })).isError, true);
    assert.equal(player.pins.list()[0].note, "Updated through MCP");
    assert.equal((await call("scormplayer_get_handoff", { ...scope, ids: ["missing"] })).isError, true);
    const panel = await call("scormplayer_show_review", scope);
    assert.equal(panel.structuredContent.pins[0].id, pin.id);
    const resource = listing.result.tools.find((tool) => tool.name === "scormplayer_show_review")._meta.ui.resourceUri;
    const html = await rpc.request("resources/read", { uri: resource });
    assert.equal(html.error, undefined, JSON.stringify(html.error));
    assert.ok(html.result.contents[0].text.includes("Send to agent"));
    assert.ok(!html.result.contents[0].text.includes("<iframe"));
    assert.deepEqual(html.result.contents[0]._meta.ui.csp, { connectDomains: [], resourceDomains: [], frameDomains: [] });
    assert.equal(panel.structuredContent.spec.state.review.pins[0].id, pin.id);
    assert.equal(pins.structuredContent.spec.root, "review");
    assert.equal(pinTool._meta["ui/resourceUri"], pinTool._meta.ui.resourceUri, "SDK retains compatibility with earlier MCP Apps hosts");
    assert.ok(!html.result.contents[0].text.includes('src="http://localhost'));
    // Even an alive PID in a registry record cannot authorize a different process's endpoint.
    fs.writeFileSync(path.join(registry, "wrong.json"), JSON.stringify({ pid: globalThis.process.ppid, port: Number(new URL(player.url).port), url: player.url }));
    const forged = (await call("scormplayer_list_players")).structuredContent.players.find((item) => item.pid === globalThis.process.ppid);
    assert.ok(forged, "forged test entry must be discovered");
    assert.equal((await call("scormplayer_get_status", { playerId: forged.playerId })).isError, true);
    assert.equal((await call("scormplayer_open_browser", { playerId: forged.playerId, revision: scope.revision })).isError, true);
  } finally { rpc.close(); await player.close(); fs.rmSync(dir, { recursive: true, force: true }); }
});

test("native Cursor package expands its root and serves tools and MCP Apps without dependencies", async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "scorm-cursor-"));
  const installed = path.join(dir, "local plugins", "scormplayer-cursor");
  const packaged = fileURLToPath(new URL("../../../dist/plugins/cursor/scormplayer-cursor/", import.meta.url));
  fs.cpSync(packaged, installed, { recursive: true });
  const manifest = JSON.parse(fs.readFileSync(path.join(installed, ".cursor-plugin", "plugin.json")));
  assert.equal(manifest.name, "scormplayer-cursor", "native identity must not collide with Cursor's imported Claude plugin");
  for (const component of ["skills", "commands", "rules"]) assert.equal(fs.statSync(path.join(installed, manifest[component])).isDirectory(), true);
  const config = JSON.parse(fs.readFileSync(path.join(installed, manifest.mcpServers))).mcpServers.scormplayer;
  assert.equal(config.type, "stdio");
  assert.deepEqual(config.args, ["${CURSOR_PLUGIN_ROOT}/server.mjs"]);
  assert.equal(config.cwd, "${CURSOR_PLUGIN_ROOT}");
  const expand = (value) => value.replaceAll("${CURSOR_PLUGIN_ROOT}", installed);
  const rpc = client(expand(config.args[0]), path.join(dir, "registry"), expand(config.cwd));
  try {
    const init = await rpc.request("initialize", { protocolVersion: "2025-06-18", capabilities: { extensions: { "io.modelcontextprotocol/ui": { mimeTypes: ["text/html;profile=mcp-app"] } } }, clientInfo: { name: "Cursor", version: "test" } });
    assert.equal(init.error, undefined, JSON.stringify(init.error));
    assert.equal(init.result.serverInfo.version, manifest.version);
    rpc.notify("notifications/initialized");
    const { result } = await rpc.request("tools/list");
    assert.ok(result.tools.some((tool) => tool.name === "scormplayer_get_progress"));
    const panel = result.tools.find((tool) => tool.name === "scormplayer_show_review");
    assert.equal(panel.annotations.readOnlyHint, true);
    assert.match(panel._meta.ui.resourceUri, /^ui:\/\//);
    const resource = await rpc.request("resources/read", { uri: panel._meta.ui.resourceUri });
    assert.equal(resource.error, undefined, JSON.stringify(resource.error));
    assert.equal(resource.result.contents[0].mimeType, "text/html;profile=mcp-app");
    assert.match(resource.result.contents[0].text, /Send to agent/);
    const players = await rpc.request("tools/call", { name: "scormplayer_list_players", arguments: {} });
    assert.deepEqual(players.result.structuredContent.players, []);
    assert.equal(fs.existsSync(path.join(installed, "node_modules")), false);
    assert.equal(fs.existsSync(path.join(installed, "extension")), false, "discovery starts no player");
  } finally { rpc.close(); fs.rmSync(dir, { recursive: true, force: true }); }
});
